# Generated by Django 2.1.15 on 2020-03-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='name',
        ),
    ]
